services:

  neo4j:
    image: neo4j:latest
    container_name: neo4j_trabalho_final
    environment:
      - NEO4J_AUTH=neo4j/senha123
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
    networks:
      - spi_network
    restart: unless-stopped

  api:
    build: ./back
    container_name: backend
    ports:
      - "3000:3000"
    env_file:
      - ./back/.env
    networks:
      - spi_network
    depends_on:
      - neo4j

  web:
    build: ./front
    container_name: front
    ports:
      - "8080:80"
    networks:
      - spi_network
    depends_on:
      - api

networks:
  spi_network:
    driver: bridge

volumes:
  neo4j_data:
  neo4j_logs:
